"""
RAG (Retrieval-Augmented Generation) service for event recommendation
- loads a FAISS vector index
- retrieves relevant event documents based on semantic similarity
- interacts with a language model (Mistral) to generate responses
- supports both general conversation and context-aware answers
"""

import faiss
import pickle
import numpy as np
import os
from sentence_transformers import SentenceTransformer
from mistralai.client import MistralClient
from mistralai.models.chat_completion import ChatMessage
from events_rag_project.config.paths import FAISS_INDEX_FILE, STORE_FILE, INTERACTIONS_LOG_FILE
from events_rag_project.config.model_options import MODEL_NAME
from events_rag_project.config.prompts import Prompts
import logging
import json
from unidecode import unidecode
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("MISTRAL_API_KEY")

class EventRAGService:
    """
    Retrieval-Augmented Generation (RAG) service for event search and recommendations
    """
     
    def __init__(self):
        """
        Initializes the RAG service
        """
        self.history = []
        self.__load_index()
        self.__load_model()

    def __load_index(self):
        """
        Loads FAISS index and associated stored texts/metadata
        """
        self.index = faiss.read_index(str(FAISS_INDEX_FILE))
        with open(STORE_FILE, "rb") as f:
            store = pickle.load(f)
        self.texts = store["texts"]
        self.metadatas = store["metadatas"]

    def __load_model(self):
        """
        Loads the sentence embedding model
        """
        logging.getLogger("sentence_transformers").setLevel(logging.ERROR)
        logging.getLogger("transformers").setLevel(logging.ERROR)
        self.model = SentenceTransformer(MODEL_NAME, local_files_only=True)
    
    def ask(self, query):
        """
        Handles a user query
        Args:
            query (str): User input message
        Returns:
            str: Return generated answer
        """
        answer = self.__call_mistral_api(Prompts.GENERAL_SYS_PROMPT, query)
        if answer == Prompts.EVENT_SEARCH_TAG:
            answer, contexts = self.ask_with_context(query)
            self.__log_interaction(query, answer, contexts)
        return answer
    
    def ask_with_context(self, query):
        """
        Handles a query requiring contextual retrieval
        Args:
            query (str): User input
        Returns:
            str: Contextual response (using RAG) generated by the LLM
            str: contexts founds in FAISS index
        """
        contextual_query, contexts = self.__build_contextual_prompt(query)
        return self.__call_mistral_api(Prompts.CONTEXTUAL_SYS_PROMPT, contextual_query), contexts
    
    def __call_mistral_api(self, system_prompt, user_prompt):
        """
        Sends a request to the Mistral API
        Args:
            system_prompt (str): Instruction prompt defining assistant behavior
            user_prompt (str): User query or contextual prompt
        Returns:
            str: Model-generated response
        """
        client = MistralClient(api_key=os.getenv("MISTRAL_API_KEY"))
        messages = [
            ChatMessage(role="system", content=system_prompt),
            *self.history,
            ChatMessage(role="user", content=user_prompt)
        ]
        response = client.chat(model="mistral-small",messages=messages)
        answer = response.choices[0].message.content.strip()
        self.__update_history(user_prompt, answer)
        return answer

    def __update_history(self, question, answer):
        """
        Updates conversation history
        Keeps only the last 3 exchanges (6 messages total)
        to limit context size.
        Args:
            question (str): User input
            answer (str): Model answer
        """
        self.history.append(ChatMessage(role="user", content=question))
        self.history.append(ChatMessage(role="assistant", content=answer))
        self.history = self.history[-6:]

    def clear_history(self):
        """
        Clear conversation history
        """
        self.history.clear()

    def __build_contextual_prompt(self, query):
        """
        Builds a contextual prompt using RAG
        Args:
            query (str): User query
        Returns:
            str: Prompt containing context + query
            str: contexts founds in FAISS index
        """
        docs = self.__search(query)
        if not docs:
            contexts = "Aucun contexte disponible."
        else:
            contexts = "\n\n".join(docs)
        return Prompts.format_contextual_prompt(contexts, query), contexts

    def __search(self, query, k=3):
        """
        Performs semantic search using FAISS
        Args:
            query (str): Input query
            k (int): Number of nearest neighbors to retrieve
        Returns:
            list[str]: Relevant results
        """
        results = []
        normalized_query = unidecode(query).lower()

        q_emb = self.model.encode([normalized_query], normalize_embeddings=True)
        q_emb = np.array(q_emb).astype("float32")
        scores, indices = self.index.search(q_emb, k) # k-> Number of returned results (standard between 3-5)
        assert(len(scores) == len(indices))
        
        # Keep and concatenate results with a scrore > 0.5 (0.4 or less is usually noise)
        for score, i in zip(scores[0], indices[0]):
            if score > 0.3:
                text = self.texts[i]
                metadata = self.metadatas[i]
                results.append(Prompts.format_text_with_metadata(text, metadata).strip())
        return results
    
    def __log_interaction(self, query, answer, contexts, ground_truth=None):
        """
        Log interaction in a json file, for future evaluation
        Args:
            query (str): Input query
            answer (str): LLM answer
            contexts (str): Contexts found in FAISS index
            ground_truth (str): 
        """
        entry = {
            "question": query,
            "answer": answer,
            "contexts": contexts,
            "ground_truth": ground_truth,
            "timestamp": datetime.utcnow().isoformat()
        }
        with open(INTERACTIONS_LOG_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
   